BloodSugarSQL2/Controllers/MeasurePageController.cs
using BloodSugar.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BloodSugar.Controllers
{
    public class MeasurePageController : Controller
    {
        public static DateTime date1 = new DateTime(2010, 1, 1, 8, 0, 0);
        public static DateTime date2 = new DateTime(2004, 1, 3, 11, 0, 0);

        public static List<BloodSugarData> bsDatas = new List<BloodSugarData>
        {

            new BloodSugarData("11231231231", date1, "morning", 12),
            new BloodSugarData("36703245432", date1, "night", 10),
            new BloodSugarData("36703124871", date1, "afternoon", 3),
            new BloodSugarData("36703245432", date1, "evening", 7),
            new BloodSugarData("36202347834", date2, "afternoon", 1),
            new BloodSugarData("36703124871", date2, "evening", 5),
            new BloodSugarData("36702347834", date2, "morning", 8),


        };
        public static List<InsulinData> iDatas = new List<InsulinData>
        {

            new InsulinData("23123124124", date1, "morning", 12),
            new InsulinData("36202347834", date2, "afternoon", 1),
            new InsulinData("36703124871", date1, "morning", 5),
            new InsulinData("36703245432", date1, "night", 10),
            new InsulinData("36702347834", date2, "morning", 8),

        };

        public static List<CarbData> cDatas = new List<CarbData>
        {

            new CarbData("643563564356", date1, "morning", 12),
            new CarbData("643563564356", date2, "afternoon", 1),
            new CarbData("36703124871", date1, "evening", 5),
            new CarbData("367033452341", date1, "night", 10),
            new CarbData("367033452341", date2, "morning", 8),
            new CarbData("367033452341", date1, "afternoon", 3),
            new CarbData("367033452341", date2, "evening", 7),
            new CarbData("367033452341", date1, "evening", 5),
            new CarbData("643563564356", date1, "night", 10),
            new CarbData("342523452345", date2, "morning", 8),


        };





        public IActionResult AddBSMeasure()
        {
            return View();
        }

        public IActionResult AddInsulinMeasure()
        {
            return View();
        }

        public IActionResult AddCarbMeasure()
        {
            return View();
        }


        public IActionResult BSMeasurePageList()
        {
            return View(bsDatas);
        }

        public IActionResult InsulinMeasurePageList()
        {
            return View(iDatas);
        }

        public IActionResult CarbMeasurePageList()
        {
            return View(cDatas);
        }





        [HttpPost]
        public IActionResult AddNewBSMeasure()
        {

            string userPhone = HttpContext.Request.Form["userPhone"];
            DateTime measureDate = DateTime.Now;
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            double mgBloodSugar = double.Parse(HttpContext.Request.Form["bloodSugar"]);



            bsDatas.Add(new BloodSugarData(userPhone, measureDate, timeOfDay, mgBloodSugar));

            return View("BSMeasurePageList", bsDatas);


        }

        [HttpPost]
        public IActionResult AddNewInsulinMeasure()
        {

            string userPhone = HttpContext.Request.Form["userPhone"];
            DateTime measureDate = DateTime.Now;
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];


            double insulin = double.Parse(HttpContext.Request.Form["insulin"]);

            iDatas.Add(new InsulinData(userPhone, measureDate, timeOfDay, insulin));


            return View("InsulinMeasurePageList", iDatas);


        }

        [HttpPost]
        public IActionResult AddNewCarbMeasure()
        {

            string userPhone = HttpContext.Request.Form["userPhone"];
            DateTime measureDate = DateTime.Now;
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            double carbs = double.Parse(HttpContext.Request.Form["carbs"]);


            cDatas.Add(new CarbData(userPhone, measureDate, timeOfDay, carbs));

            return View("CarbMeasurePageList", cDatas);


        }

        /*
        [HttpPost]
        public IActionResult AddNewBS() //blood sugar
        {
            int userId = int.Parse(HttpContext.Request.Form["userId"]);
            double mgBloodSugar = double.Parse(HttpContext.Request.Form["bloodSugar"]);
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            //adds this data to bloodSugarDatas
            bloodSugarDatas.Add(new BloodSugarData(userId, mgBloodSugar, timeOfDay));
            
            return view $$$$
        }

        [HttpPost]
        public IActionResult AddNewID() //insulin dose
        {
            int userId = int.Parse(HttpContext.Request.Form["userId"]);
            double mgInsulinDose = double.Parse(HttpContext.Request.Form["insulinDose"]);
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            insulinData.Add(new InsulinData(userId, DateTime.Now, timeOfDay, mgInsulinDose));
        }

        [HttpPost]
        public IActionResult AddNewCM() //carbon meal
        {
            int userId = int.Parse(HttpContext.Request.Form["userId"]);
            double mgBloodSugar = double.Parse(HttpContext.Request.Form["bloodSugar"]);
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            carbDatas.Add(new CarbData(userId, DateTime.Now, timeOfDay, grCarbIntake));
        }
        */




    };

}

BloodSugarSQL2/Controllers/UserPageController.cs
using BloodSugar.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BloodSugar.Controllers
{
    public class UserPageController : Controller
    {

        public static List<UserInfo> userInfos = new List<UserInfo>()
        {
            new UserInfo("Jesse", "123 Main St", "555-234-7443", new DateTime(1984, 6, 3)),
            new UserInfo("Mike", "453 Hudson St", "555-777-3333", new DateTime(1974, 3, 8)),
            new UserInfo("Walt", "123 Main St", "155-234-7343", new DateTime(1972, 6, 11)),
            new UserInfo("Saul", "123 Main St", "555-234-7443", new DateTime(1970, 6, 3)),
            new UserInfo("Hank", "123 Main St", "555-234-7443", new DateTime(1964, 6, 3)),
            new UserInfo("Gus", "123 Main St", "555-234-7443", new DateTime(1962, 6, 3)),
            new UserInfo("Skyler", "123 Main St", "555-234-7443", new DateTime(1960, 6, 3)),


        };



        public IActionResult AddUser()
        {
            return View();
        }

        public IActionResult UserPageList()
        {
            return View(userInfos);
        }



        [HttpPost]
        public IActionResult AddNewUser() //from UserPage.AddUser
        {

            string name = HttpContext.Request.Form["name"];
            string address = HttpContext.Request.Form["address"];
            string phone = HttpContext.Request.Form["phone"];
            DateTime birthDay = DateTime.Parse(HttpContext.Request.Form["birthDay"]);


            userInfos.Add(new UserInfo(name, address, phone, birthDay));

            return View("UserPageList", userInfos);

            /*
            Datas datas = new Datas();
            UserInfo userInfos = new UserInfo();

            userInfos.Name = name;
            userInfos.Address = address;
            userInfos.Phone = phone;
            userInfos.BirthDay = birthDay;
             */


        }















    }
}

BloodSugarSQL2/Views/Shared/_Layout.cshtml
@*use site css elements*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -      BloodSugar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BloodSugar.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BloodSugar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <nav>

                
                    <a class="x" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    
                    <a class="x" asp-area="" asp-controller="UserPage" asp-action="UserPageList">User list</a>
                    <a class="x" asp-area="" asp-controller="UserPage" asp-action="AddUser">Add user</a>
                

                    @*
                    <a class="x" asp-area="" asp-controller="MeasurePage" asp-action="AddBSMeasure">Add BS</a>
                    <a class="x" asp-area="" asp-controller="MeasurePage" asp-action="AddInsulinMeasure">Add Insulin</a>
                    <a class="x" asp-area="" asp-controller="MeasurePage" asp-action="AddCarbMeasure">Add Carb</a>
                    *@
        
                    <a class="x" asp-area="" asp-controller="MeasurePage" asp-action="BSMeasurePageList">Blood Sugar</a>
                    <a class="x" asp-area="" asp-controller="MeasurePage" asp-action="InsulinMeasurePageList">Insulin</a>
                    <a class="x" asp-area="" asp-controller="MeasurePage" asp-action="CarbMeasurePageList">Carb</a>

                    
                    
                




                <div class="animation start-home"></div>
        </nav>
     </header>
        
        

        
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>