BloodSugarSQL2/Controllers/DiagramPageController.cs
using BloodSugar.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace BloodSugar.Controllers
{
    public class DiagramPageController : Controller
    {
        private readonly ILogger<DiagramPageController> _logger;

        public DiagramPageController(ILogger<DiagramPageController> logger)
        {
            _logger = logger;
        }

        public IActionResult BSDiagram()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BloodSugarSQL2/Controllers/MeasurePageController.cs
using BloodSugar.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BloodSugar.Controllers
{
    public class MeasurePageController : Controller
    {
        public static DateTime date1 = new DateTime(2010, 1, 1, 8, 0, 0);
        public static DateTime date2 = new DateTime(2004, 1, 3, 11, 0, 0);

        public static List<BloodSugarData> bsDatas = new List<BloodSugarData>
        {

            new BloodSugarData("11231231231", date1, "morning", 12),
            new BloodSugarData("36703245432", date1, "night", 10),
            new BloodSugarData("36703124871", date1, "afternoon", 3),
            new BloodSugarData("36703245432", date1, "evening", 7),
            new BloodSugarData("36202347834", date2, "afternoon", 1),
            new BloodSugarData("36703124871", date2, "evening", 5),
            new BloodSugarData("36702347834", date2, "morning", 8),


        };
        public static List<InsulinData> iDatas = new List<InsulinData>
        {

            new InsulinData("23123124124", date1, "morning", 12),
            new InsulinData("36202347834", date2, "afternoon", 1),
            new InsulinData("36703124871", date1, "morning", 5),
            new InsulinData("36703245432", date1, "night", 10),
            new InsulinData("36702347834", date2, "morning", 8),

        };

        public static List<CarbData> cDatas = new List<CarbData>
        {

            new CarbData("643563564356", date1, "morning", 12),
            new CarbData("643563564356", date2, "afternoon", 1),
            new CarbData("36703124871", date1, "evening", 5),
            new CarbData("367033452341", date1, "night", 10),
            new CarbData("367033452341", date2, "morning", 8),
            new CarbData("367033452341", date1, "afternoon", 3),
            new CarbData("367033452341", date2, "evening", 7),
            new CarbData("367033452341", date1, "evening", 5),
            new CarbData("643563564356", date1, "night", 10),
            new CarbData("342523452345", date2, "morning", 8),


        };





        public IActionResult AddBSMeasure()
        {
            return View();
        }

        public IActionResult AddInsulinMeasure()
        {
            return View();
        }

        public IActionResult AddCarbMeasure()
        {
            return View();
        }


        public IActionResult BSMeasurePageList()
        {
            return View(bsDatas);
        }

        public IActionResult InsulinMeasurePageList()
        {
            return View(iDatas);
        }

        public IActionResult CarbMeasurePageList()
        {
            return View(cDatas);
        }





        [HttpPost]
        public IActionResult AddNewBSMeasure()
        {

            string userPhone = HttpContext.Request.Form["userPhone"];
            DateTime measureDate = DateTime.Now;
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            double mgBloodSugar = double.Parse(HttpContext.Request.Form["bloodSugar"]);



            bsDatas.Add(new BloodSugarData(userPhone, measureDate, timeOfDay, mgBloodSugar));

            return View("BSMeasurePageList", bsDatas);


        }

        [HttpPost]
        public IActionResult AddNewInsulinMeasure()
        {

            string userPhone = HttpContext.Request.Form["userPhone"];
            DateTime measureDate = DateTime.Now;
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];


            double insulin = double.Parse(HttpContext.Request.Form["insulin"]);

            iDatas.Add(new InsulinData(userPhone, measureDate, timeOfDay, insulin));


            return View("InsulinMeasurePageList", iDatas);


        }

        [HttpPost]
        public IActionResult AddNewCarbMeasure()
        {

            string userPhone = HttpContext.Request.Form["userPhone"];
            DateTime measureDate = DateTime.Now;
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            double carbs = double.Parse(HttpContext.Request.Form["carbs"]);


            cDatas.Add(new CarbData(userPhone, measureDate, timeOfDay, carbs));

            return View("CarbMeasurePageList", cDatas);


        }

        /*
        [HttpPost]
        public IActionResult AddNewBS() //blood sugar
        {
            int userId = int.Parse(HttpContext.Request.Form["userId"]);
            double mgBloodSugar = double.Parse(HttpContext.Request.Form["bloodSugar"]);
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            //adds this data to bloodSugarDatas
            bloodSugarDatas.Add(new BloodSugarData(userId, mgBloodSugar, timeOfDay));
            
            return view $$$$
        }

        [HttpPost]
        public IActionResult AddNewID() //insulin dose
        {
            int userId = int.Parse(HttpContext.Request.Form["userId"]);
            double mgInsulinDose = double.Parse(HttpContext.Request.Form["insulinDose"]);
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            insulinData.Add(new InsulinData(userId, DateTime.Now, timeOfDay, mgInsulinDose));
        }

        [HttpPost]
        public IActionResult AddNewCM() //carbon meal
        {
            int userId = int.Parse(HttpContext.Request.Form["userId"]);
            double mgBloodSugar = double.Parse(HttpContext.Request.Form["bloodSugar"]);
            string timeOfDay = HttpContext.Request.Form["timeOfDay"];

            carbDatas.Add(new CarbData(userId, DateTime.Now, timeOfDay, grCarbIntake));
        }
        */




    };

}

BloodSugarSQL2/Views/MeasurePage/AddBSMeasure.cshtml

@{
    using (Html.BeginForm("AddNewBSMeasure", "MeasurePage", FormMethod.Post))
    {
        
        <div class="text-center" style="font-size: 150%">
            <h1 class="display-4">Add new Blood Sugar measurement</h1>

            <h2 class="lead">Please fill in the form below</h2>

            <form method="post" >
                

                <label for="userPhone">Phone</label>
                <input type="text" class="form-control" name="userPhone" id="userPhone" placeholder="Enter your phone number">

                <label for="sugar">Blood Sugar mg/dl</label>
                <input type="number" class="form-control" name="bloodSugar" id="bloodSugar" placeholder="Enter your blood sugar level (mg/dl)">

            

                
                 <label for="time">Time of day</label>
                 <select class="form-control" name="timeOfDay" id="timeOfDay">
                        <option value="beforeBreakfast">Before breakfast</option>
                        <option value="afterBreakfast">After breakfast</option>
                        <option value="beforeLunch">Before lunch</option>
                        <option value="afterLunch">After lunch</option>
                        <option value="beforeDinner">Before dinner</option>
                        <option value="afterDinner">After dinner</option>
                        <option value="night">Night</option>
                 </select>
                                            
                            
                        
                <br>
            
                <button type="submit" class="button">Submit</button>
            </form>
        </div>
    }
}

BloodSugarSQL2/Views/MeasurePage/AddCarbMeasure.cshtml

@{
    using (Html.BeginForm("AddNewCarbMeasure", "MeasurePage", FormMethod.Post))
    {

        <div class="text-center" style="font-size: 150%">
                    <h1 class="display-4">Add new Carb measurement</h1>

                    <h2 class="lead">Please fill in the form below</h2>

                    <form method="post" >


                        <label for="userPhone">Phone</label>
                        <input type="text" class="form-control" name="userPhone" id="userPhone" placeholder="Enter your phone number">

                        <label for="carbs">Carbs g</label>
                        <input type="number" class="form-control" name="carbs" id="carbs" placeholder="Enter your carbs level (gramm)">



                         <label for="time">Time of day</label>
                         <select class="form-control" name="timeOfDay" id="timeOfDay">
                                <option value="beforeBreakfast">Before breakfast</option>
                                <option value="afterBreakfast">After breakfast</option>
                                <option value="beforeLunch">Before lunch</option>
                                <option value="afterLunch">After lunch</option>
                                <option value="beforeDinner">Before dinner</option>
                                <option value="afterDinner">After dinner</option>
                                <option value="night">Night</option>
                         </select>



                        <br>

                        <button type="submit" class="button">Submit</button>
                    </form>
        </div>
    }
}

BloodSugarSQL2/Views/MeasurePage/AddInsulinMeasure.cshtml

@{
    using (Html.BeginForm("AddNewInsulinMeasure", "MeasurePage", FormMethod.Post))
    {

        <div class="text-center" style="font-size: 150%">
                    <h1 class="display-4">Add new Insulin measurement</h1>

                    <h2 class="lead">Please fill in the form below</h2>

                    <form method="post" >


                        <label for="userPhone">Phone</label>
                        <input type="text" class="form-control" name="userPhone" id="userPhone" placeholder="Enter your phone number">


                        <label for="insulin">Insulin mg/dl</label>
                        <input type="number" class="form-control" name="insulin" id="insulin" placeholder="Enter your insulin level (mg/dl)">




                         <label for="time">Time of day</label>
                         <select class="form-control" name="timeOfDay" id="timeOfDay">
                                <option value="beforeBreakfast">Before breakfast</option>
                                <option value="afterBreakfast">After breakfast</option>
                                <option value="beforeLunch">Before lunch</option>
                                <option value="afterLunch">After lunch</option>
                                <option value="beforeDinner">Before dinner</option>
                                <option value="afterDinner">After dinner</option>
                                <option value="night">Night</option>
                         </select>



                        <br>

                        <button type="submit" class="button">Submit</button>
                    </form>
        </div>
    }
}

BloodSugarSQL2/Views/MeasurePage/BSMeasurePageList.cshtml
@model List<BloodSugarData>


            @*modify and remove button for each row in table*@

<html>
    <table>
        <td> Phone </td>
        <td> Date </td>
        <td> Time of day </td>
        <td> Blood sugar (mg/dl)</td>
        <td> Delete </td>
        <td> Modify </td>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.userPhone </td>
                <td>@item.measureDate </td>
                <td>@item.timeOfDay </td>
                <td>@item.mgBloodSugar </td>
                <td>
                        <form asp-action="Delete" asp-controller="MeasurePage" method="post">
                                <input type="hidden" name="userPhone" value="@item.userPhone" />
                            <input type="submit" value="Delete" />
                        </form>
                </td>
                <td>
                        <form asp-action="Modify" asp-controller="MeasurePage" method="post">
                                <input type="hidden" name="userPhone" value="@item.userPhone" />
                            <input type="submit" value="Modify" />
                        </form>
                </td>
            </tr>
        }
    </table>
    <div class="modal-footer">
        <div class="text-center" style="font-size: 150%">

            <a class="linkt" asp-area="" asp-controller="MeasurePage" asp-action="AddBSMeasure">Add New Blood Sugar Data</a>
            <a class="linkt" asp-area="" asp-controller="DiagramPage" asp-action="BSDiagram">Blood Sugar Data Diagram</a>
            

        </div>
    </div>  


    
@*  -      -           -           -            -   GOOGLE CHART PART    -      -           -           -            -          -            - *@
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart', 'bar']});
      google.charts.setOnLoadCallback(drawStuff);

      function drawStuff() {

        var button = document.getElementById('change-chart');
        var chartDiv = document.getElementById('chart_div');

        var data = google.visualization.arrayToDataTable([

        @Html.Raw($"['User Phone', 'Date', 'Time of Day', 'Blood Sugar (mg/dl)'],")
        @foreach (var item in Model)
        {
            @Html.Raw($"['{@item.userPhone}', {@item.measureDate}, {@item.timeOfDay}, {@item.mgBloodSugar}],")
        }
        ]);


        var materialOptions = {
          width: 900,
          chart: {
            title: 'Nearby galaxies',
            subtitle: 'distance on the left, brightness on the right'
          },
          series: {
            0: { axis: 'distance' }, // Bind series 0 to an axis named 'distance'.
            1: { axis: 'brightness' } // Bind series 1 to an axis named 'brightness'.
          },
          axes: {
            y: {
              distance: {label: 'parsecs'}, // Left y-axis.
              brightness: {side: 'right', label: 'apparent magnitude'} // Right y-axis.
            }
          }
        };

        

        function drawMaterialChart() {
          var materialChart = new google.charts.Bar(chartDiv);
          materialChart.draw(data, google.charts.Bar.convertOptions(materialOptions));
          button.innerText = 'Change to Classic';
          button.onclick = drawClassicChart;
        }

        

        drawMaterialChart();
    };
    </script>
  </head>
  <body>

    <br><br>
    <div id="chart_div" style="width: 800px; height: 500px;"></div>
  </body>




      <div>

            <button type="button"  
                style=" margin-left:45px;"   class="button" onclick=" window.location.href = '@Url.Action("AddMeasure", "MeasurePage")' ">Add measure
            </button>
    </div>
















@*



    <div>
        <table>
            <th>
                <td>User Phone</td>
                <td>Date</td> 
                <td>Time of Day</td> 
                <td>Blood Sugar (mg/dl)</td>
            </th>
        
            @foreach (var item in Model)
            {
                <tr>
                    <td></td>  
                    <td>@item.userPhone </td><td>@item.measureDate </td>
                    <td>@item.timeOfDay </td>
                    <td>@item.mgBloodSugar </td>


                </tr>
            }
        
        
        </table>

    </div>





        @*
    ------------------------------------------------------------------------------------
    ------------------------------------------------------------------------------------
    ------------------------------------------------------------------------------------
        @


    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
          google.charts.load('current', {'packages':['bar']});
          google.charts.setOnLoadCallback(drawChart);

          function drawChart() {
            var data = google.visualization.arrayToDataTable([
              ['User Phone', 'Date', 'Time of Day', 'Blood Sugar (mg/dl)'],
              ['2014', 1000, 400, 200],
              ['2015', 1170, 460, 250],
              ['2016', 660, 1120, 300],
              ['2017', 1030, 540, 350]
            ]);

            var options = {
              chart: {
                title: 'Company Performance',
                subtitle: 'Sales, Expenses, and Profit: 2014-2017',
              }
            };

            var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

            chart.draw(data, google.charts.Bar.convertOptions(options));
          }
        </script>

          <body>
        <div id="columnchart_material" style="width: 800px; height: 500px;"></div>
      </body>

        @*
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <script type="text/javascript">
              google.charts.load('current', {'packages':['bar']});
              google.charts.setOnLoadCallback(drawChart);

              function drawChart() {

                var data = google.visualization.arrayToDataTable([

                    @Html.Raw($"['User Phone', 'Date', 'Time of Day', 'Blood Sugar (mg/dl)'],")
                    @foreach (var item in Model)
                    {
                        @Html.Raw($"['{@item.userPhone}', {@item.measureDate}, {@item.timeOfDay}, {@item.mgBloodSugar}],")

                    }
                ]);

                var options = {

                    title: 'Blood Sugar'

                };

                var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

                chart.draw(data, google.charts.Bar.convertOptions(options));
              }
            </script>
  
          <body>
            <div id="columnchart_material" style="width: 800px; height: 500px;"></div>
          </body>
        *@ 
        

 </html>

BloodSugarSQL2/Views/MeasurePage/CarbMeasurePageList.cshtml
@model List<CarbData> 

<table>
    @foreach (var item in Model)
    {
        <tr>
            <td></td>  
            <td>@item.userPhone </td><td>@item.measureDate </td>
            <td>@item.timeOfDay </td>
            <td>@item.gCarb </td>
        </tr>
    }
</table>

<div class="modal-footer">
    <div class="text-center" style="font-size: 150%">

        <a class="linkt" asp-area="" asp-controller="MeasurePage" asp-action="AddCarbMeasure">Add New Carb Data</a>

    </div>
</div>   
    
    

BloodSugarSQL2/Views/MeasurePage/InsulinMeasurePageList.cshtml
@model List<InsulinData>    

<table>
@foreach (var item in Model)
{
    <tr>
        <td></td>  
        <td>@item.userPhone </td><td>@item.measureDate </td>
        <td>@item.timeOfDay </td>
        <td>@item.mgInsulin </td>
    </tr>
}
</table>

<div class="modal-footer">
    <div class="text-center" style="font-size: 150%">
        
        <a class="linkt" asp-area="" asp-controller="MeasurePage" asp-action="AddInsulinMeasure">Add New Insulin Data</a>

    </div>
</div>